launch:
  - arg:
      name: "map_config"
      default: "$(find-pkg-share map)/data/map_6.geojson"
  - node:
      pkg: "routing"
      exec: "routing_node"
      name: "routing_node"
      output: "log"
      param:
        - { name: "map_config", value: "$(var map_config)" }

        - name: "route"
          param:
            - { name: "max_ego_dist", value: 2.0 }
            - { name: "postfix_len", value: 2.0 }
            - { name: "spline_step", value: 0.2 }

        - name: "mesh"
          param:
            - { name: "dist", value: 2.8 }
            - { name: "offset", value: 1.2 }

        - name: "graph"
          param:
            - { name: "k_nearest_mode", value: false }
            - { name: "k_nearest", value: 15 }
            - { name: "search_radius", value: 7.0 }
