services:
  truck:
    container_name: "${CONTAINER_NAME:-truck-${USER}}"
    image: "registry.robotics-lab.ru/truck:0.11.1"
    privileged: true
    runtime: "${DOCKER_RUNTIME:-runc}"
    build:
      dockerfile: Dockerfile
      context: .
      x-bake:
        platforms:
          - linux/arm64
          - linux/amd64
        cache-from:
          - type=registry,ref=registry.robotics-lab.ru/truck:cache-arm64
          - type=registry,ref=registry.robotics-lab.ru/truck:cache-amd64
        cache-to:
          # - type=registry,ref=registry.robotics-lab.ru/truck:cache-arm64
          # - type=registry,ref=registry.robotics-lab.ru/truck:cache-amd64
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
      - "${VIDEO_STREAMING_PORT:-8889}:8889"
    volumes:
      - "${PWD}:/truck"
      - "/dev:/dev"

networks:
  default:
    name: "${CONTAINER_NAME:-truck-${USER}}"
