readingDataPointsFilters:
- MinDistDataPointsFilter:
    minDist: 0.1
- MaxDistDataPointsFilter:
    maxDist: 40.0

referenceDataPointsFilters:
- MinDistDataPointsFilter:
    minDist: 0.1
- MaxDistDataPointsFilter:
    maxDist: 40.0

matcher:
  KDTreeMatcher:
    knn: 1
    epsilon: 0

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.75

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 100
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4

inspector:
 NullInspector

logger:
  NullLogger
